// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PruebaTecnicaSeven.Models;

public partial class Tareas
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public int? Estado { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? IdProyecto { get; set; }
}