// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PruebaTecnicaSeven.Models;

public partial class UsuarioProyecto
{
    public int Id { get; set; }

    public int? UsuarioId { get; set; }

    public int? ProyectoId { get; set; }
}